GET http://localhost:3000

#####

POST http://localhost:3000

{
    "nombre": "cuatro leches"
}

### Eliminar un producto por nombre clase 04/04/2025
DELETE http://localhost:3000

{
    "nombre": "Red velvet"
}
